### ISSUE TITLE
Migrate to `nextcloud-libraries` (?)

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/vue-select#35]
Upstream is basically inactive and we are the most active fork.
Also while there are some little changes by upstream it does not seem that our accessibility related work is going to be merged.

So we need to maintain this anyway for us. We also publish this package under our organization,
so I think it makes sense to move this to [nextcloud-libraries](https://github.com/nextcloud-libraries) also to get potential contributions.
But especially to make work on this easier (we strongly need the vue 3 version for nextcloud-vue 9).

(And also the Security tab is :ghost: )

What do you think? @Pytal @ShGKme 

Also CC @AndyScherzinger

**Comment by susnux** [comment]
BTW @raimund-schluessler already asked this here and in many month nothing on the upstream side changed :pensive: 

https://github.com/nextcloud-deps/vue-select/pull/25#issuecomment-1752149817

**Comment by AndyScherzinger** [comment]
Yes, totally agree 👍

**Comment by Pytal** [comment]
Good with me +1

And feel free to take the reins for v4 @susnux :)
